---
- name: Install Docker Swarm
  when: docker_network_driver is defined and docker_network_driver=="overlay"
  include_role: { name: atosatto.docker-swarm } 
  vars:
    skip_docker_py: True
    skip_docker_compose: True
    docker_swarm_interface: "{{ swarm_interface }}"

- name: Install Docker
  when: docker_network_driver is defined and docker_network_driver=="bridge"
  include_role: { name: atosatto.docker-swarm } 
  vars:
    skip_swarm: True
    python_pip_packages: "docker"

- include_tasks: "create_network.yml"

- name: Ensure additional pip docker packages are installed
  pip:
    name: "{{ item }}"
    state: latest
  ignore_errors: yes
  when: (ansible_distribution == 'Ubuntu') and (ansible_distribution_major_version | int > 16)
  loop:
    "{{ docker_pip_packages }}"

- name: Setup node_exporter
  import_tasks: monitoring.yml
  when: configure_monitoring|bool


# - name: Get info on docker containers
#   when: force_images|default(false)
#   docker_host_info:
#     containers: yes
#     containers_filters:  
#       #ancestor: "{{ image_openresty }}"
#       name: openresty
#   register: docker_image_info

# - name: Stop running containers
#   when: force_images|default(false)
#   docker_container:
#     name: "{{ item }}"
#     state: stopped
#   loop: "{{ docker_image_info.containers | map(attribute='Id') | list }}"  